# Generated by Django 4.1.7 on 2023-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
