# Generated by Django 4.1.7 on 2023-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='etching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='landscape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='stamp',
            field=models.BooleanField(default=False),
        ),
    ]
